### ISSUE TITLE
KeyError from create_application

### ISSUE THREAD

**Issue by brianmay** [django/daphne#205]
Since upgrading to Channels 2, I get a number of these errors. I suspect this happens when restarting the deployed instance:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/daphne/http_protocol.py", line 160, in process
    "server": self.server_addr,
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/daphne/server.py", line 191, in create_application
    ), loop=asyncio.get_event_loop())
KeyError: <WebRequest at 0x7ff738677710 method=GET uri=/api/internal/projects/21/managed_objects/ clientproto=HTTP/1.1>
```

Unfortunately, it doesn't help that there is a lot happening on this line, and I am not sure what part causes this error.

**Comment by brianmay** [comment]
Here is another error I get about at the the same time:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
StopIteration: <Queue maxsize=0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/daphne/http_protocol.py", line 166, in process
    "body": self.content.read(),
ValueError: I/O operation on closed file.
```

**Comment by andrewgodwin** [comment]
- Does this happen every single restart? Or just sometimes?
- What does your routing look like? Are you using channel layers?
- What versions are you running of `daphne`, `channels`, `asgiref`, `channels-redis`, and `twisted`?

**Comment by brianmay** [comment]
Only seems to happen when shutting down the docker container on deployment. Seems to happen repeatedly. So far my attempts to reproduce it on my own box have failed.

Routing is pretty simple:

```
application = ProtocolTypeRouter({

    "websocket": AuthMiddlewareStack(
        URLRouter([
            url("^ws/$", CumulocityConsumer),
        ])
    ),

    "channel": ChannelNameRouter({
        "lcl": LclConsumer,
    }),

})
```
Latest versions of everything:

```
asgiref==2.3.0
channels_redis==2.2.1
channels==2.1.1
daphne==2.1.1
```

I noticed that Twisted isn't pinned, however, I imagine it will be the latest version, which I think is Twisted==17.9.0

**Comment by andrewgodwin** [comment]
OK - unless this can be reproduced locally/reliably somehow, I can't solve it, so I'll leave this ticket open as "blocked" for a few weeks and then I'll have to close it as unreproduceable.

**Comment by tarek-aec** [comment]
Hi everybody,

I have the same issue:
```python
2018-05-31 08:55:41,789 - ERROR - http_protocol - Traceback (most recent call last):
  File "/home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
StopIteration: <Queue maxsize=0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/daphne/http_protocol.py", line 166, in process
    "body": self.content.read(),
ValueError: I/O operation on closed file.
2018-05-31 08:55:42,138 - ERROR - http_protocol - Traceback (most recent call last):
  File "/home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
StopIteration: <Queue maxsize=0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/daphne/http_protocol.py", line 166, in process
    "body": self.content.read(),
ValueError: I/O operation on closed file.

2018-05-31 08:55:52,453 - WARNING - server - Application instance <Task pending coro=<__call__() running at /home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/channels/http.py:180> wait_for=<Future pending cb=[Task._wakeup()]>> for connection <WebRequest at 0x7fd4745f2fd0 method=GET uri=/static/ckeditor/ckeditor/plugins/scayt/skins/moono-lisa/scayt.css clientproto=HTTP/1.1> took too long to shut down and was killed.
2018-05-31 08:55:52,454 - WARNING - server - Application instance <Task pending coro=<__call__() running at /home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/channels/http.py:180> wait_for=<Future pending cb=[Task._wakeup()]>> for connection <WebRequest at 0x7fd4742d7fd0 method=GET uri=/static/ckeditor/ckeditor/plugins/tableselection/styles/tableselection.css clientproto=HTTP/1.1> took too long to shut down and was killed.
2018-05-31 08:55:52,454 - WARNING - server - Application instance <Task pending coro=<__call__() running at /home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/channels/http.py:180> wait_for=<Future pending cb=[Task._wakeup()]>> for connection <WebRequest at 0x7fd4742d7048 method=GET uri=/static/ckeditor/ckeditor/plugins/scayt/dialogs/dialog.css clientproto=HTTP/1.1> took too long to shut down and was killed.
2018-05-31 08:55:52,454 - WARNING - server - Application instance <Task pending coro=<__call__() running at /home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/channels/http.py:180> wait_for=<Future pending cb=[Task._wakeup()]>> for connection <WebRequest at 0x7fd4746671d0 method=GET uri=/static/ckeditor/ckeditor/skins/moono-lisa/editor_gecko.css?t=H8DA clientproto=HTTP/1.1> took too long to shut down and was killed.
2018-05-31 08:55:52,455 - WARNING - server - Application instance <Task pending coro=<__call__() running at /home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/channels/http.py:180> wait_for=<Future pending cb=[Task._wakeup()]>> for connection <WebRequest at 0x7fd4742c9438 method=GET uri=/static/ckeditor/ckeditor/config.js?t=H8DA clientproto=HTTP/1.1> took too long to shut down and was killed.
```
I used the same versions:
```
asgiref==2.3.0
channels_redis==2.2.1
channels==2.1.1
daphne==2.1.1
Twisted==18.4.0
```
is there any suggestion, thank you.

**Comment by JohnDoee** [comment]
```
Traceback (most recent call last):
  File "/home/tarek/Documents/python/lms-mt/env/lib/python3.5/site-packages/daphne/http_protocol.py", line 166, in process
    "body": self.content.read(),
ValueError: I/O operation on closed file.
```

Twisted closes "content" when the connection is lost, i.e. request is "finished" internally in Twisted. I fixed it by checking `if self.content.closed:` before initiating the request handling where content is read.

Similar error only happened for me when using nginx as reverse proxy and I was able to reproduce it consistently when I found a working way to trigger it.

**Comment by tarek-aec** [comment]
Thank you @JohnDoee when I downgrade `channels` and `daphne` versions to `2.1.0`, the issue solved.
```
channels==2.1.0
daphne==2.1.0
```

**Comment by andrewgodwin** [comment]
I have added the check you suggested, @JohnDoee . If someone could confirm this is fixed on `master` Daphne, then I can close this and issue a release.

**Comment by brianmay** [comment]
Reference to commit that (hopefully) fixed this: ece52b8e7958b41c86fd89830bc7814368e42bde

**Comment by brianmay** [comment]
This patch did not fix the problem I mentioned in the first post. However, then I fixed what I thought should be a completely unrelated error in my application and the problem seems to have disappeared. Will keep an eye on it over the next several days and close this bug report if the problem doesn't reoccur.

**Comment by brianmay** [comment]
Closing this for now as it no longer occurring for me - at least in master. Will reopen if the problem reoccurs.

**Comment by nilsabdi** [comment]
This sadly occurs for me, but ONLY when I have Debug=False.

**Comment by brianmay** [comment]
I also saw it once more too :-(.

**Comment by brianmay** [comment]
```
protocol==<WebRequest at 0x10cb326d8 method=GET uri=/api/v1/ clientproto=HTTP/1.1>
```
The following code fails: `self.connections[protocol]` with KeyError.

I am wondering if this really is a valid protocol??

**Comment by thomas-riccardi** [comment]
I encountered the issue when starting daphne on a machine where the CPU was already used at 100%: very high load avg, everything is slow.

Probable scenario:
- start daphne on a machine where the CPU was already used at 100%
- nginx in front of daphne as a reverse-proxy (`proxy_pass`)
- curl on nginx, with 1s timeout
- curl timeout is reached: daphne didn't have time to answer the request because of low available CPU
- curl closes the connection
- nginx closes the connection to daphne?
- daphne error:
```
2018-06-20 15:09:42,378 daphne.http_protocol ERROR    Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/daphne/http_protocol.py", line 160, in process
    "server": self.server_addr,
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/dist-packages/daphne/server.py", line 191, in create_application
    ), loop=asyncio.get_event_loop())
KeyError: <WebRequest at 0x7f47280e7550 method=GET uri=/ clientproto=HTTP/1.1>
```
(`daphne==2.1.0`)


I'm not 100% sure this is the main case (in fact instead of curl it's a kubernetes readinessProbe) because I mostly have the following nginx error:
```
2018/06/20 15:10:21 [error] 6#6: *1523 connect() failed (111: Connection refused) while connecting to upstream, client: 10.28.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8001/", host: "10.28.0.66:80"
10.28.0.1 - - [20/Jun/2018:15:10:21 +0000] "GET / HTTP/1.1" 502 174 "-" "kube-probe/1.9+" "-" rt=0.001 uct=0.000 uht=0.000 urt=0.000
```

Anyway, I suspect that during the async call in `server.py: create_application`:
```
        # Run it, and stash the future for later checking
        self.connections[protocol]["application_instance"] = asyncio.ensure_future(application_instance(
            receive=input_queue.get,
            send=lambda message: self.handle_reply(protocol, message),
        ), loop=asyncio.get_event_loop())

**Comment by andrewgodwin** [comment]
Have you tried Daphne `2.2.0`? It has a fix for applications not being created when a connection is closed prematurely.

**Comment by brianmay** [comment]
For the record, I wanted to be sure that the error came from the `self.connections[protocol]` lookup and not something happening on the RHS of the = assignment. I made the following change:

```diff
commit 26105fb130980d3ba709e75bd03ed1835c9ce48b
Author: Brian May <brian@linuxpenguins.xyz>
Date:   Wed Jun 13 10:22:21 2018 +1000

    Add error handling

diff --git a/daphne/server.py b/daphne/server.py
index 6a65ebb..83c4989 100755
--- a/daphne/server.py
+++ b/daphne/server.py
@@ -185,6 +185,8 @@ class Server(object):
         input_queue = asyncio.Queue()
         application_instance = yield deferToThread(self.application, scope=scope)
         # Run it, and stash the future for later checking
+        if protocol not in self.connections:
+            raise RuntimeError("Protocol %r is not in self.connections!" % protocol)
         self.connections[protocol]["application_instance"] = asyncio.ensure_future(application_instance(
             receive=input_queue.get,
             send=lambda message: self.handle_reply(protocol, message),
```

This gave the following error (so far only once...):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/daphne/http_protocol.py", line 160, in process
    "server": self.server_addr,
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/daphne/server.py", line 189, in create_application
    raise RuntimeError("Protocol %r is not in self.connections!" % protocol)
RuntimeError: Protocol <WebRequest at 0x7fc9f83e2a20 method=GET uri=/ clientproto=HTTP/1.1> is not in self.connections!
```

To me it this does sound like this should be fixed in 2.2.0. I plan on deploying 2.2.0, and I expect to get no errors. Which doesn't actually prove anything, unfortunately.

**Comment by brianmay** [comment]
I got this error at the top almost immediately when the new version started. :-(

**Comment by thomas-riccardi** [comment]
@andrewgodwin 
> Have you tried Daphne 2.2.0? It has a fix for applications not being created when a connection is closed prematurely.

I assume you are talking about this commit: ece52b8e7958b41c86fd89830bc7814368e42bde

As I understand it, this commit avoids errors after the call to `server.create_application`, whereas the initial issue (that I also encounter) seems to be *in* `server.create_application`.

@brianmay seems to be on the right track: the `yield` + `@inlineCallbacks` makes this call async; maybe  letting some other code removing the `protocol` from `self.connections` ? This call was made async in daphne 2.1.0 by a7ccfab4952790307646cad6d9584961b3023162

**Comment by brianmay** [comment]
WIth the following change:

```
commit 7e884ea0b7d3e8a977ce6141441bb901947df8d1
Author: Brian May <brian@linuxpenguins.xyz>
Date:   Wed Jun 13 10:22:21 2018 +1000

    Add debugging for https://github.com/django/daphne/issues/205

diff --git a/daphne/server.py b/daphne/server.py
index 6a65ebb..0d7d753 100755
--- a/daphne/server.py
+++ b/daphne/server.py
@@ -163,10 +163,12 @@ class Server(object):
         """
         if protocol in self.connections:
             raise RuntimeError("Protocol %r was added to main list twice!" % protocol)
+        logger.info("protocol %r connected" % protocol)
         self.connections[protocol] = {"connected": time.time()}
 
     def protocol_disconnected(self, protocol):
         # Set its disconnected time (the loops will come and clean it up)
+        logger.info("protocol %r disconnected" % protocol)
         self.connections[protocol]["disconnected"] = time.time()
 
     ### Internal event/message handling
@@ -185,6 +187,9 @@ class Server(object):
         input_queue = asyncio.Queue()
         application_instance = yield deferToThread(self.application, scope=scope)
         # Run it, and stash the future for later checking
+        logger.info("protocol %r create_application" % protocol)
+        if protocol not in self.connections:
+            raise RuntimeError("Protocol %r is not in self.connections!" % protocol)
         self.connections[protocol]["application_instance"] = asyncio.ensure_future(application_instance(
             receive=input_queue.get,
             send=lambda message: self.handle_reply(protocol, message),
@@ -246,6 +251,7 @@ class Server(object):
                 del self.connections[protocol]["application_instance"]
                 application_instance = None
             # Check to see if protocol is closed and app is closed so we can remove it
+            logger.info("protocol %r deleted" % protocol)
             if not application_instance and disconnected:
                 del self.connections[protocol]
         reactor.callLater(1, self.application_checker)
```

I am getting the following logged for a particular protocol:

```
protocol <WebRequest at 0x7fed45dac048 method=(no method yet) uri=(no uri yet) clientproto=(no clientproto yet)> connected
protocol <WebRequest at 0x7fed45dac048 method=GET uri=/health_check/ clientproto=HTTP/1.1> deleted
protocol <WebRequest at 0x7fed45dac048 method=GET uri=/health_check/ clientproto=HTTP/1.1> deleted
protocol <WebRequest at 0x7fed45dac048 method=GET uri=/health_check/ clientproto=HTTP/1.1> deleted
protocol <WebRequest at 0x7fed45dac048 method=GET uri=/health_check/ clientproto=HTTP/1.1> deleted
protocol <WebRequest at 0x7fed45dac048 method=GET uri=/health_check/ clientproto=HTTP/1.1> disconnected
protocol <WebRequest at 0x7fed45dac048 method=GET uri=/health_check/ clientproto=HTTP/1.1> deleted
protocol <WebRequest at 0x7fed45dac048 method=GET uri=/health_check/ clientproto=HTTP/1.1> create_application
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/daphne/http_protocol.py", line 160, in process
    "server": self.server_addr,
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/daphne/server.py", line 192, in create_application
    raise RuntimeError("Protocol %r is not in self.connections!" % protocol)
RuntimeError: Protocol <WebRequest at 0x7fed45dac048 method=GET uri=/health_check/ clientproto=HTTP/1.1> is not in self.connections!
```

I don't understand why there are so many "deleted" being display, especially before the "disconnected" - maybe logging is changing the order of the messages? It does appear however that the connection is being deleted before the create_application is called.

**Comment by brianmay** [comment]
Ignore my confusion (which I edited and deleted). I intended to put the deleted message under the if condition, not above it. So I imagine only the last deleted after message really is a deleted message, after the disconnected message. Will fix and retest.

**Comment by brianmay** [comment]
Here are the messages I am now getting after fixing that if:

```
protocol <WebRequest at 0x7faf28f1dc50 method=(no method yet) uri=(no uri yet) clientproto=(no clientproto yet)> connected
protocol <WebRequest at 0x7faf28f1dc50 method=HEAD uri=/ clientproto=HTTP/1.1> disconnected
protocol <WebRequest at 0x7faf28f1dc50 method=HEAD uri=/ clientproto=HTTP/1.1> deleted
protocol <WebRequest at 0x7faf28f1dc50 method=HEAD uri=/ clientproto=HTTP/1.1> create_application
```

`create_application` is being executed after the connection has been disconnected and deleted, so naturally it is going to crash.

**Comment by brianmay** [comment]
Maybe something like the following??? Hopefully I haven't left the state of the calling object in a broken/inconsistant way...

```patch
diff --git a/daphne/http_protocol.py b/daphne/http_protocol.py
index 1155135..3ff10be 100755
--- a/daphne/http_protocol.py
+++ b/daphne/http_protocol.py
@@ -160,7 +160,7 @@ class WebRequest(http.Request):
                     "server": self.server_addr,
                 })
                 # Check they didn't close an unfinished request
-                if self.content.closed:
+                if self.application_queue is None or self.content.closed:
                     # Not much we can do, the request is prematurely abandoned.
                     return
                 # Run application against request
diff --git a/daphne/server.py b/daphne/server.py
index 6a65ebb..f796a4e 100755
--- a/daphne/server.py
+++ b/daphne/server.py
@@ -185,6 +187,9 @@ class Server(object):
         input_queue = asyncio.Queue()
         application_instance = yield deferToThread(self.application, scope=scope)
         # Run it, and stash the future for later checking
+        logger.info("protocol %r create_application" % protocol)
+        if protocol not in self.connections:
+            return None
         self.connections[protocol]["application_instance"] = asyncio.ensure_future(application_instance(
             receive=input_queue.get,
             send=lambda message: self.handle_reply(protocol, message),
diff --git a/daphne/ws_protocol.py b/daphne/ws_protocol.py
index 9edfce6..a7331b5 100755
--- a/daphne/ws_protocol.py
+++ b/daphne/ws_protocol.py
@@ -75,8 +75,9 @@ class WebSocketProtocol(WebSocketServerProtocol):
                 "server": self.server_addr,
                 "subprotocols": subprotocols,
             })
-            self.application_deferred.addCallback(self.applicationCreateWorked)
-            self.application_deferred.addErrback(self.applicationCreateFailed)
+            if self.application_deferred is not None:
+                self.application_deferred.addCallback(self.applicationCreateWorked)
+                self.application_deferred.addErrback(self.applicationCreateFailed)
         except Exception as e:
             # Exceptions here are not displayed right, just 500.
             # Turn them into an ERROR log.
```

**Comment by andrewgodwin** [comment]
Something like that, yes. Could you open a pull request with that (and remove that extra logging) and I'll merge it in?
