### ISSUE TITLE
--proxy-headers error

### ISSUE THREAD

**Issue by NotSqrt** [django/daphne#78]
Hi,

I just tested `daphne` with `--proxy-headers` behind a nginx server, and got the following exception when my browser initiates the websocket connection:

```
2017-02-07 15:13:43,115 ERROR    Traceback (most recent call last):
  File "/path/ve/local/lib/python2.7/site-packages/daphne/ws_protocol.py", line 62, in onConnect
    self.requestHeaders,
AttributeError: 'WebSocketProtocol' object has no attribute 'requestHeaders'
```

I'm using the channels-examples/databinding app with the following virtualenv content:
```
appdirs==1.4.0
asgi-redis==1.0.0
asgiref==1.0.0
autobahn==0.17.1
channels==1.0.3
constantly==15.1.0
daphne==1.0.2
Django==1.10.5
incremental==16.10.1
msgpack-python==0.4.8
packaging==16.8
pyparsing==2.1.10
redis==2.10.5
six==1.10.0
Twisted==16.6.0
txaio==2.6.0
uWSGI==2.0.14
zope.interface==4.3.3
```

Is it a version compatibility issue, or a bug maybe ?

Thanks !

**Comment by andrewgodwin** [comment]
It might be - could you try downgrading to Twisted 16.4 and Autobahn 0.13? I know those have worked in the past.

**Comment by NotSqrt** [comment]
It appears that #73 makes daphne 1.0.2 incompatible with `autobahn<0.15`.

I downgraded to daphne==1.0.1, but even with `Twisted==16.4 autobahn==0.13`, it still produces the same exception.

**Comment by JohnDoee** [comment]
@andrewgodwin Where does that `requestHeaders` variable even come from ?

Autobahn has been using the attribute `http_headers` for a long time, [as far as I can see](https://github.com/crossbario/autobahn-python/blob/v0.13.0/autobahn/websocket/protocol.py#L2427).

The self.requestHeaders would only make sense in a method on http.Request.

**Comment by NotSqrt** [comment]
What seems available at https://github.com/django/daphne/blob/1.0.2/daphne/ws_protocol.py#L61 is `self.clean_headers`, a list of tuples `(header_name_lowercase_ascii, value)`, so not an instance of `twisted.web.http_headers.Headers` as used in `daphne.tests.test_utils`

**Comment by andrewgodwin** [comment]
I'm not sure why the person who submitted that PR wrote it that way, but I've changed it to `http_headers` and modified the utility function so it'll understand both types. It works locally, but I'd appreciate one of you trying it out too to confirm before I do a release.

**Comment by NotSqrt** [comment]
I'll check on Monday.

**Comment by whs** [comment]
I'm still having problem with 630609fce70528d906ebbe0dbb8f04a5fb162eb6. (Please see #81 for other dependencies version in my case)

```
2017-02-11 21:55:52,795 ERROR    Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/daphne/ws_protocol.py", line 65, in onConnect
    self.client_addr
  File "/usr/local/lib/python3.6/site-packages/daphne/utils.py", line 21, in parse_x_forwarded_for
    if headers.hasHeader(address_header_name):
AttributeError: 'dict' object has no attribute 'hasHeader'
```

**Comment by andrewgodwin** [comment]
Ah, I had forgotten to push up the second commit, 7d1123d - try that.

**Comment by whs** [comment]
Seems that automated testing is failing for that commit.

**Comment by andrewgodwin** [comment]
That's what I get for not running tests. Fixed now.

**Comment by whs** [comment]
I don't see any newer commits, have you pushed? :P

**Comment by whs** [comment]
Seems to be working for me. Thanks!

**Comment by whs** [comment]
I checked again and it seems that my WebSocket connections are stuck in the pending state. After 50 seconds the connection got closed. I'm guessing it is due to #82 and not related to the fix of this issue.

**Comment by NotSqrt** [comment]
@andrewgodwin It appears it's not completely fixed : 

* in `daphne.http_protocol`, `parse_x_forwarded_for` is called with a `twisted.web.http_headers.Headers` instance, whose values are lists as in the tests.
* but in `daphne.ws_protocol`, `parse_x_forwarded_for` is called now with a dict thanks to your fix, but whose values are strings, not lists. So currently we end up with the first character on the 'X-Forwarded-For' string.

**Comment by andrewgodwin** [comment]
Odd, the `ws_protocol` headers was also a dict of lists when I checked with ipdb. I'll double check and then bring in your PR.

**Comment by andrewgodwin** [comment]
Yup, I must have been looking at the wrong thing. Merged!
